# This file was generated by GoReleaser. DO NOT EDIT.
class Wio < Formula
  desc "C/C++ development environment"
  homepage "https://github.com/wio/wio"
  url "https://github.com/wio/wio/releases/download/v0.10.0/wio_0.10.0_macOS_64bit.tar.gz"
  version "0.10.0"
  sha256 "4be1046a21e0196bdf366656a222db78d8b12474ffdfee81b3f01c23548f6103"

  def install
    bin.install "wio"
  end

  test do
    system "#{bin}/wio --version"
  end
end
