# This file was generated by GoReleaser. DO NOT EDIT.
class Wio < Formula
  desc "C/C++ development environment"
  homepage "https://github.com/wio/wio"
  url "https://github.com/wio/wio/releases/download/v0.10.0/wio_0.10.0_macOS_64bit.tar.gz"
  version "0.10.0"
  sha256 "fa9d32b45f8efeb1d5330ba1044db2489e684726a6a8606bd7e5724ffa37faf2"

  def install
    bin.install "wio"
  end

  test do
    system "#{bin}/wio --version"
  end
end
